blog/urls.py
from django.conf.urls import patterns, url

from blog import views

urlpatterns = patterns('',
    url(r'author/(?P<author_name>[a-zA-Z0-9-_]+)$', views.author, name='author'),
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'(?P<post_slug>.*)', views.detail, name='detail'),
)

django_tutorial/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

urlpatterns = patterns('',
    url(r'^admin/', include(admin.site.urls)),
    url(r'^blog/', include('blog.urls', namespace='blog')),
    url(r'^polls/', include('polls.urls', namespace='polls')),
    url(r'^login/$', 'django.contrib.auth.views.login', {'template_name': 'account/login.html'}),
    url(r'^logout/$', 'django.contrib.auth.views.logout', {'next_page': '/blog/'}),
)

polls/urls.py
from django.conf.urls import patterns, url

from polls import views

urlpatterns = patterns('',
    url(r'^$', views.IndexView.as_view(), name='index'),
    # ex: /polls/5/
    url(r'^(?P<pk>\d+)/$', views.DetailView.as_view(), name='detail'),
    # ex: /polls/5/results/
    url(r'^(?P<pk>\d+)/results/$', views.ResultsView.as_view(), name='results'),
    # ex: /polls/5/vote/
    url(r'^(?P<question_id>\d+)/vote/$', views.vote, name='vote'),
)

blog/models.py
import datetime
import json

from django.db import models
from django.utils import timezone
from annoying.fields import JSONField

class Author(models.Model):
    nickname = models.CharField(max_length=64, unique=True)
    email = models.EmailField()
    created_on = models.DateTimeField(auto_now_add=True)
    updated_on = models.DateTimeField(auto_now=True)

    def __unicode__(self):
        return self.nickname

    def __str__(self):
        return unicode(self).encode('utf8')


class Post(models.Model):
    title = models.CharField(max_length=100)
    slug = models.CharField(max_length=100, default='', unique=True)
    author = models.ForeignKey(Author)
    pub_date = models.DateTimeField('date published')
    content = models.TextField(max_length=20000)
    keywords = JSONField(blank=True, null=True)

    def __unicode__(self):
        return self.title

    def __str__(self):
        return unicode(self).encode('utf8')

    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)

    was_published_recently.admin_order_field = 'pub_date'
    was_published_recently.boolean = True
    was_published_recently.short_description = 'Published_recently?'


class Comment(models.Model):
    post = models.ForeignKey(Post)
    pub_date = models.DateTimeField('date published')
    content = models.TextField(max_length=500)

    def __unicode__(self):
        return self.content

    def __str__(self):
        return unicode(self).encode('utf8')

polls/models.py
import datetime

from django.db import models
from django.utils import timezone

class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    def __unicode__(self):
        return self.question_text

    def __str__(self):
        return unicode(self).encode('utf-8')

    def was_published_recently(self):
        now = timezone.now()
        return timezone.now() - datetime.timedelta(days=1) <= self.pub_date <= now


class Choice(models.Model):
    question = models.ForeignKey(Question)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __unicode__(self):
        return self.choice_text

    def __str__(self):
        return unicode(self).encode('utf-8')

blog/views.py
import re

from django.shortcuts import render, get_object_or_404, redirect
from django.utils import timezone
from django.views.generic import CreateView
from django.contrib.auth.decorators import login_required

from models import Post, Author, Comment


class IndexView(CreateView):
    template_name = 'blog/index.html'
    context_object_name = 'ps'

    def get(self, request, *args, **kwargs):
        ps = Post.objects.order_by('-pub_date')[:10]
        return render(request, 'blog/index.html', {'ps': ps, 'title': 'Blog Index', 'user': request.user})

    @login_required()
    def post(self, request, *args, **kwargs):
        a = get_object_or_404(Author, nickname='bearzk')
        title = request.POST['title'].strip()
        slug = re.sub('\s', '-', title.lower())
        p = a.post_set.create(title=title, slug=slug, content=request.POST['content'],
                              pub_date=timezone.now())
        p.save()
        return redirect('blog:index')

def detail(request, post_slug):
    p = get_object_or_404(Post, slug=post_slug)
    a = get_object_or_404(Author, pk=p.author_id)
    cs = Comment.objects.filter(post_id=p.id)
    return render(request, 'blog/detail.html', {'p': p, 'a': a, 'cs': cs})


def author(request, author_name):
    a = get_object_or_404(Author, nickname=author_name)
    return render(request, 'blog/author.html', {'a': a})

polls/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.views import generic
from django.utils import timezone

from polls.models import Question, Choice


class IndexView(generic.ListView):
    template_name = 'polls/index.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        return Question.objects.filter(
            pub_date__lte=timezone.now()
        ).order_by('-pub_date')[:5]


class DetailView(generic.DetailView):
    model = Question
    template_name = 'polls/detail.html'

    def get_queryset(self):
        return Question.objects.filter(pub_date__lte=timezone.now())

class ResultsView(generic.DetailView):
    model = Question
    template_name = 'polls/results.html'


# def index(request):
#     latest_question_list = Question.objects.order_by('-pub_date')[:5]
#     return render(request, 'polls/index.html', {'latest_question_list': latest_question_list})
#
# def detail(request, question_id):
#     question = get_object_or_404(Question, pk=question_id)
#     return render(request, 'polls/detail.html', {'question': question})
#
# def results(request, question_id):
#     question = get_object_or_404(Question, pk=question_id)
#     return render(request, 'polls/results.html', {'question': question})

def vote(request, question_id):
    q = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = q.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        return render(request, 'polls/detail.html', {
            'question': q,
            'error_message': "You didn't seletc a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        return redirect('polls:results', q.id)

templates/blog/add.html
<form action="{% url 'blog:add' %}" method="post">
    {% csrf_token %}
    <input type="text" name="title">
    <input type="text" name="content">
    <input type="submit" value="post">
</form>

templates/blog/author.html
{{ a }}

templates/blog/detail.html
{% load staticfiles %}
<head>
    <link rel="stylesheet" type="text/css" href="{% static 'blog/detail.css' %}" />
</head>
<body>
{% if error_message %}{% endif %}
<div class="container">
    <h1>
        {{ p }}
        <span class="right"><a href="{% url 'blog:author' a %}">{{ a }}</a></span>
    </h1>
    <p class="content-text">{{ p.content }}</p>

    <div id="disqus_thread"></div>
    <script type="text/javascript">
        /* * * CONFIGURATION VARIABLES: EDIT BEFORE PASTING INTO YOUR WEBPAGE * * */
        var disqus_shortname = 'bearzk'; // required: replace example with your forum shortname

        /* * * DON'T EDIT BELOW THIS LINE * * */
        (function() {
            var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
            dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
            (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
        })();
    </script>
    <noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>

    <a class="right" href="{% url 'blog:index' %}">back to index</a>
</div>
</body>

templates/blog/index.html
{% extends 'generic/base.html' %}
{% block content %}
<div class="container pure-g">
    {% for p in ps %}
    <div class="pure-u-1-2">
        <h2><a href="{% url 'blog:detail' p.slug %}">{{ p.title }}</a></h2>
        <p>by <a href="{% url 'blog:author' p.author %}">{{ p.author }}</a> on {{ p.pub_date.date }}</p>
    </div>
    {% endfor %}
    <form class='pure-form pure-form-aligned pure-u-1 pure-g' action="{% url 'blog:index' %}" method="post">
        {% csrf_token %}
        <fieldset>
            <div class="pure-control-group">
                <label for="blog-title">Title</label>
                <input id="blog-title" type="text" name="title" placeholder="title">
            </div>

            <div class="pure-control-group">
                <label for="blog-body">Content</label>
                <textarea id="blog-body" type="text" name="content" placeholder="content" rows="20" cols="50"></textarea>
            </div>

            <div class="pure-control-group">
                <label for="blog-submit"></label>
                <input id="blog-submit" class="pure-button pure-button-primary" type="submit" value="post">
            </div>
        </fieldset>
    </form>
</div>
{% endblock %}

templates/generic/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
<head lang="en">
    <meta charset="UTF-8">
    <title>
        {{ title }}
    </title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="http://yui.yahooapis.com/pure/0.5.0/pure-min.css">
    <link rel="stylesheet" href="http://yui.yahooapis.com/pure/0.5.0/grids-responsive-old-ie-min.css">
    <link rel="stylesheet" href="http://yui.yahooapis.com/pure/0.5.0/grids-responsive-min.css">
    <link rel="stylesheet" type="text/css" href="{% static 'blog/index.css' %}"/>
</head>
<body>
    <header>{% include 'generic/header.html' %}</header>
    {% block content %}{% endblock %}
    <footer>{% include 'generic/footer.html' %}</footer>
</body>
</html>

templates/generic/footer.html
{% load staticfiles %}
<div class="header-container pure-g">
    <div class="header-logo pure-u-1-4">
        <a href="{% url 'blog:index' %}" title="bearzk blog">
            <img src="{% static 'img/logo.png' %}">
        </a>
    </div>
    <div class="header-message pure-u-1-4"></div>
    <div class="header-user pure-u-1-4">{{ request.user }}</div>
    <div class="header-login-out pure-u-1-4">
        copyright &copy; {% now "Y" %}
    </div>
</div>

templates/generic/header.html
{% load staticfiles %}
<div class="pure-g">
    <div class="header-block pure-u-1-4">
        <a href="{% url 'blog:index' %}" title="bearzk blog">
            <img src="{% static 'img/logo.png' %}">
        </a>
    </div>
    <div class="header-block pure-u-1-4"></div>
    <div class="header-block pure-u-1-4">{{ user }}</div>
    <div class="header-block pure-u-1-4">
            <a href="/logout/">logout</a>
            <a href="/login/">login</a>
    </div>
</div>

templates/polls/detail.html
<h1>{{ question.question_text }}</h1>
{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'polls:vote' question.id %}" method="post">
{% csrf_token %}
{% for choice in question.choice_set.all %}
    <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}" />
    <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br />
{% endfor %}
<input type="submit" value="vote" />
</form>

<a href="{% url 'polls:index' %}">Back to Index</a>

templates/polls/index.html
{% load staticfiles %}
<link rel="stylesheet", type="text/css" href="{% static 'polls/style.css' %}"/>
{% if latest_question_list %}
    <ul>
        {% for question in latest_question_list %}
            <li><a href="{% url 'polls:detail' question.id %}">{{question.question_text}}</a></li>
        {% endfor %}
    </ul>
{% else %}
    <p>No question yet.</p>
{% endif %}

templates/polls/results.html
<h1>{{ question.question_text }}</h1>

<ul>
    {% for choice in question.choice_set.all %}
        <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
    {% endfor %}
</ul>

<a href="{% url 'polls:detail' question.id %}">Vote again?</a>

<a href="{% url 'polls:index' %}">Back to Index</a>